#syntax=docker/dockerfile:1.7.0-labs

ARG BASE_IMAGE
FROM ${BASE_IMAGE}

COPY --parents src/**/package.xml /packagexmls/

RUN apt-get update && \
    rosdep update --rosdistro=humble && \
    rosdep install --rosdistro=humble \
    --from-paths /packagexmls/ --ignore-src -y

RUN rm -r /packagexmls

RUN apt-get update && apt-get install -y \
    tmux
